### ISSUE TITLE
Prepare for Demo (Working System)

### ISSUE THREAD

**Issue by suphaphan** [suphaphan/CSC440TopDollarDeals#10]
This will be completed or close on the day of presentation.

**Comment by philip-wernersbach** [comment]
Here's what I'm thinking on the demo:
1. Create a user.
2. Login with the user.
3. Update the user's info.
4. Create an item.
5. Add an item.
6. Update the item info.
7. Delete the item.
8. Delete the user.

That will give people a good idea of what the app does, since it runs through a whole bunch of flows.

**Comment by suphaphan** [comment]
Phil agreed to do the Demo
